### ISSUE TITLE
TCP 章翻译错误

### ISSUE THREAD

**Issue by gky99** [luohaha/Chinese-uvbook#15]
“大多数的设置函数是同步的，因为它们不会消耗太多cpu资源”

不是不消耗太多资源，而是指运行速度由CPU速度限制（类似于运算密集，而不是io密集）

不知道怎么翻译的concrete一些

**Comment by luohaha** [comment]
是的，这里原文说的是Most of the setup functions are synchronous since they are CPU-bound（cpu密集型，计算密集型）的意思，忘了为啥我以前这么翻译了。不过直接翻译也不对，比较一个设置函数说cpu密集太过了。。我调整下吧

**Comment by luohaha** [comment]
修改为“大多数的设置函数是同步的，因为它们毕竟不是io操作。”
